# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Página pessoal - Rodrigo Lima
email: Rodrigo.Lima@ZethaSolutions.Com
footertitle: Dados para contato
footersubtitle: Rodrigo Lima
email2: rlimasp@gmail.com
celular: (11) 9 7192 1520
description: Essa página contém detalhes sobre o perfil profissional do analista de sistemas e consultor SAP Business One, Rodrigo Lima.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rodrigozetha.github.io/" # the base hostname & protocol for your site
twitter_username: rodrigozetha
github_username:  rodrigozetha

# Build settings
markdown: kramdown
